Fix golint non-style issues
xeals/signal-back pull request #42
Opened 2018-11-28 09:29 UTC by nezorflame

2018-11-28 12:01 UTC, xeals requested changes
Mostly okay, couple of changes or clarifications I'd like.

What linter is this? `golint` isn't giving these unused result warnings for me. Nothing I've used ever suggested the change similar to that made in `types/util.go`'s `rescue` function either.

2018-11-28 12:01 UTC, xeals commented on types/backup.go
> +			return errors.Wrap(readErr, "failed to read attr")
Why call it `readErr` through here?

Also, `att` is short for "attachment", not "attribute". Still worth fixing, but fix it to the right word.

2018-11-28 12:01 UTC, xeals commented on types/backup.go
> +		return nil, errors.Wrap(err, "unable to write frame to file")
This is `ReadFull`, not `WriteFull`. It's reading from the file into a buffer; the error doesn't make sense.

2018-11-28 14:40 UTC, nezorflame commented
I stand corrected - these warnings are produced by `golangci-lint`, which uses multiple linters internally.
These warnings were given by it.
Most of the changes are fixes for the warning of the `errcheck` linter, which checks for the missing error checks in the code.
The warning given was `Error return value of `io.ReadFull` is not checked (errcheck)`

2018-11-28 14:42 UTC, nezorflame commented on types/backup.go
> +			return errors.Wrap(readErr, "failed to read attr")
This is the warning given by `govet`: `declaration of "err" shadows declaration at backup.go:154 (govet)`

2018-11-28 14:44 UTC, nezorflame commented on types/backup.go
> +		return nil, errors.Wrap(err, "unable to write frame to file")
OK, just skipping the error here then.

2018-11-28 14:50 UTC, nezorflame commented
There are still some warnings left, but they are mostly non-essential.
If you'd like, I can post you the full output here.

2018-11-28 22:39 UTC, xeals commented on types/backup.go
> +			return errors.Wrap(readErr, "failed to read attr")
Shadowing `err` doesn't matter given that it's already handled the last time it's declared. It's interesting that the linter would pick out a common Go pattern. That warning can be ignored.

2019-05-24 01:39 UTC, dolanor commented on types/backup.go
> +	_, _ = io.ReadFull(bf.file, frame)
What's the point of removing this error handling?

2019-05-30 13:21 UTC, nezorflame commented on types/backup.go
> +			return errors.Wrap(readErr, "failed to read attr")
Hi, sorry for disappearing :)
I've removed `readErr` and fixed remaining linter issues.

2019-05-30 13:23 UTC, nezorflame commented
Ready to be reviewed again.
Also I've added initial Go modules support since dependency management is pretty stable these days (we use it at my work in production without any issues).

2019-07-02 19:24 UTC, m0 commented
Thanks for adding the modules @nezorflame! You might want to split the module patch and the style changes into two separate PRs for easier review. While I have no opinion about the style changes, I think the added modules are a great improvement.

2019-07-23 15:36 UTC, nezorflame commented
@m0 @xeals as requested, I've separated style changes with the module PR (see #61).

So far it seems that all the essential `golangci-lint` issues have been addressed.

2025-02-17 22:55 UTC, closed without merging